/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsString, IsOptional, ValidateNested } from "class-validator";
import { MenuUpdateManyWithoutUsersInput } from "./MenuUpdateManyWithoutUsersInput";
import { Type } from "class-transformer";
import { TableUpdateManyWithoutUsersInput } from "./TableUpdateManyWithoutUsersInput";
@InputType()
class UserUpdateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  firstName?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  lastName?: string | null;

  @ApiProperty({
    required: false,
    type: () => MenuUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => MenuUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => MenuUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  menus?: MenuUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  password?: string;

  @ApiProperty({
    required: false,
    type: [String],
  })
  @IsString({
    each: true,
  })
  @IsOptional()
  @Field(() => [String], {
    nullable: true,
  })
  roles?: Array<string>;

  @ApiProperty({
    required: false,
    type: () => TableUpdateManyWithoutUsersInput,
  })
  @ValidateNested()
  @Type(() => TableUpdateManyWithoutUsersInput)
  @IsOptional()
  @Field(() => TableUpdateManyWithoutUsersInput, {
    nullable: true,
  })
  tables?: TableUpdateManyWithoutUsersInput;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  username?: string;
}
export { UserUpdateInput };
