/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/docs/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsBoolean, IsOptional, ValidateNested } from "class-validator";
import { DiscountCreateNestedManyWithoutOrdersInput } from "./DiscountCreateNestedManyWithoutOrdersInput";
import { Type } from "class-transformer";
import { ProductCreateNestedManyWithoutOrdersInput } from "./ProductCreateNestedManyWithoutOrdersInput";
import { TableWhereUniqueInput } from "../../table/base/TableWhereUniqueInput";
@InputType()
class OrderCreateInput {
  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  approved?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => DiscountCreateNestedManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => DiscountCreateNestedManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => DiscountCreateNestedManyWithoutOrdersInput, {
    nullable: true,
  })
  discounts?: DiscountCreateNestedManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  payed?: boolean | null;

  @ApiProperty({
    required: false,
    type: () => ProductCreateNestedManyWithoutOrdersInput,
  })
  @ValidateNested()
  @Type(() => ProductCreateNestedManyWithoutOrdersInput)
  @IsOptional()
  @Field(() => ProductCreateNestedManyWithoutOrdersInput, {
    nullable: true,
  })
  products?: ProductCreateNestedManyWithoutOrdersInput;

  @ApiProperty({
    required: false,
    type: () => TableWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => TableWhereUniqueInput)
  @IsOptional()
  @Field(() => TableWhereUniqueInput, {
    nullable: true,
  })
  table?: TableWhereUniqueInput | null;
}
export { OrderCreateInput };
